name: user_manager
description: User management API.
publish_to: none
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_facebook_auth: 1.0.2 #^2.0.2
  cloud_firestore: ^0.16.0
  shared_preferences: '>=0.5.12+4 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.4
  mockito: ^4.1.3
  pedantic: ^1.9.0
  cloud_firestore_mocks: ^0.6.0
