name: real_time_location
description: A Real time location service.
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^3.2.1
  geocoding: ^1.0.5
  firebase_database: ^6.0.0
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  mockito: ^4.1.3
  firebase_database_mocks: ^0.1.0+3

publish_to: none